---
- name: Creating Virtual Private Cloud
  command: sleep 15

- name: Creating VPC Subnet on Availability Zone A
  command: sleep 10

- name: Creating VPC Subnet on Availability Zone B
  command: sleep 10

- name: Creating NGINX Security Group
  ec2_group:
    name: nginx-secgroup
    description: nginx az a & b security group
    vpc_id: vpc-a70b1ac0
    region: ap-southeast-1
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    
- name: Creating Load Balancer Security Group
  ec2_group:
    name: lb-secgroup
    description: nginx lb security group
    vpc_id: vpc-a70b1ac0
    region: ap-southeast-1
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
